# Ticket content for antholim/Pulse. See README.md for how to add tickets.
#
# Tokens like {E3} or {S1-11} are replaced with real issue references (#N)
# once the issues exist. An acceptance criterion or task starting with "[x] "
# is rendered as already checked.

# iteration number -> (milestone title, due date, release it belongs to)
ITERATIONS = {
    1: ("Iteration 1", "Oct 6, 2026", "Release 1"),
    2: ("Iteration 2", "Oct 20, 2026", "Release 1"),
    3: ("Iteration 3", "Nov 3, 2026", "Release 1"),
    4: ("Iteration 4", "Nov 17, 2026", "Release 1"),
    5: ("Iteration 5", "Dec 1, 2026", "Release 2"),
    6: ("Iteration 6", "Dec 15, 2026", "Release 2"),
    7: ("Iteration 7", "Jan 19, 2027", "Release 2"),
    8: ("Iteration 8", "Feb 5, 2027", "Release 2"),
    9: ("Iteration 9", "Feb 16, 2027", "Final Release"),
    10: ("Iteration 10", "Mar 2, 2027", "Final Release"),
    11: ("Iteration 11", "Mar 16, 2027", "Final Release"),
    12: ("Iteration 12", "Mar 30, 2027", "Final Release"),
    13: ("Iteration 13", "Apr 13, 2027", "Final Release"),
}

# release -> iteration number it is delivered in. The release name is also
# the label added to every issue planned for it.
RELEASES = {
    "Release 1": 4,
    "Release 2": 8,
    "Final Release": 13,
}

NEW_LABELS = [
    ("epic", "3E4B9E", "Parent ticket grouping related work across the project"),
    ("user-story", "0E8A16", "Feature described from the user's point of view"),
    ("task", "C5DEF5", "Technical or setup work"),
    ("spike", "FBCA04", "Time-boxed research or decision"),
    ("Release 1", "B60205", "Planned for Release 1 (Iteration 4, due Nov 17, 2026)"),
    ("must", "D93F0B", "MUST priority in the proposal MVP boundary"),
    ("should", "F9D0C4", "SHOULD priority in the proposal MVP boundary"),
    ("could", "EDEDED", "COULD priority in the proposal MVP boundary"),
    ("infra", "5319E7", "Infrastructure and cross-cutting code"),
    ("security", "000000", "Security and privacy"),
    ("design", "BFD4F2", "Architecture, domain and UI design"),
    ("project-mgmt", "0052CC", "Planning, process and course deliverables"),
]

# ---------------------------------------------------------------- EPICS
EPICS = [
    dict(
        key="E1",
        title="Epic: Project Foundation & DevOps",
        labels=["epic", "DevOps & CI", "infra", "must"],
        goal="Give the team a reliable, repeatable engineering setup so every feature ships through the same quality gates.",
        scope=[
            "Repository structure and contribution conventions",
            "Linting, formatting and pre-commit hooks",
            "CI pipeline running lint, tests, coverage and Docker builds on every push and PR",
            "Docker and docker-compose setup for all services",
            "Central logging and error handling",
            "Test framework, mocking and coverage tooling",
            "Security baseline: secrets management, input validation, dependency scanning",
            "Hosted demo environment (later releases, if needed for rollout)",
        ],
        success=[
            "A new teammate can clone the repo, run `docker compose up` and get a working app",
            "Every PR runs lint, tests and coverage, and the build fails on any error",
        ],
        out_of_scope=[],
    ),
    dict(
        key="E2",
        title="Epic: COLLECT: Data Connectors & Import",
        labels=["epic", "Data Connectors", "must"],
        goal="Reliably retrieve information from 2 to 3 representative sources, with CSV and JSON import as universal options.",
        scope=[
            "CSV and JSON import with validation and row-level error reporting",
            "One adapter per external source, so a changed API only touches that adapter",
            "Raw payload archive kept for reprocessing and debugging",
            "Every ingestion recorded as a sync run so it can be repeated and compared",
            "Incremental sync and pagination for large sources",
        ],
        success=[
            "Repeated ingestion from more than one representative source (proposal MVP indicator)",
        ],
        out_of_scope=[
            "Connectors beyond the agreed 2 to 3 sources (COULD, only once the core workflow is stable)",
        ],
    ),
    dict(
        key="E3",
        title="Epic: RESOLVE: Normalization & Entity Resolution",
        labels=["epic", "Entity Resolution", "Manual Match Review", "must"],
        goal="Decide whether records from different sources refer to the same real-world company or person, with a stated confidence and preserved provenance.",
        scope=[
            "Normalization of names, legal suffixes, domains, emails and phone numbers",
            "Tier 1 deterministic matching: normalized name plus domain",
            "Tier 2 fuzzy matching: string similarity (for example rapidfuzz `token_sort_ratio`) with a threshold between 85 and 90 percent",
            "People matching: normalized full name plus a secondary signal (company, email or handle); name-only matching documented as a known MVP limitation",
            "Outcomes: Match, Possible Match (review) or No Match, each storing its basis and confidence",
            "Labelled validation set of 30 to 40 real entity pairs, balanced between matches and non-matches",
            "Precision, recall and F1, with false positives weighted more heavily than false negatives",
            "Manual review queue for uncertain matches (SHOULD)",
        ],
        success=[
            "The matching approach is evaluated against a labelled sample and the results are documented and explainable",
        ],
        out_of_scope=[
            "A learned classifier (no labelled training data)",
            "AI-assisted matching as a required dependency (optional exploration only)",
            "Synthetic data for the evaluation: it would measure the rules that generated it, not real-world variation",
        ],
    ),
    dict(
        key="E4",
        title="Epic: ORGANIZE: Unified Data Model & Entity Profiles",
        labels=["epic", "Unified Data Model", "Entity Profiles", "must"],
        goal="Store resolved companies, people, topics, events and activity in one consistent structure.",
        scope=[
            "Unified Data Model schema: entities, source records, provenance, relationships and historical states",
            "Versioned migrations and indexes",
            "Data model documentation (a proposal output)",
            "Entity profile page consolidating everything known about one entity (SHOULD)",
        ],
        success=[
            "Data from different sources lives in one model, and every field can be traced back to its source record",
        ],
        out_of_scope=[],
    ),
    dict(
        key="E5",
        title="Epic: MONITOR: Synchronization, Historical State & Change Tracking",
        labels=["epic", "Change Tracking", "Historical Timeline", "must"],
        goal="Know what was added, modified or removed since the previous synchronization.",
        scope=[
            "Re-run connected sources on demand or on a schedule",
            "Preserve selected historical states (snapshots) per sync run",
            "Detect added, modified and removed records between two sync points",
            "Change log per source and per entity",
            "Historical timeline showing how an entity evolved (SHOULD)",
        ],
        success=[
            "Two sync points can be preserved and compared (proposal MVP indicator)",
        ],
        out_of_scope=[],
    ),
    dict(
        key="E6",
        title="Epic: COMPARE: Activity Metrics & Trend Detection",
        labels=["epic", "Activity Scoring", "Trend Detection", "must"],
        goal="Show what is becoming more or less active over time, using measures anyone can reproduce.",
        scope=[
            "A small set of transparent metrics based on frequency, recency and volume of activity",
            "The inputs behind every score are recorded",
            "Period-over-period comparison",
            "Classification of entities, topics or categories as growing, declining or stable",
            "Configurable weights and thresholds (SHOULD)",
        ],
        success=[
            "Every metric can be traced to underlying data and reproduced by hand (proposal MVP indicator)",
        ],
        out_of_scope=[
            "Opaque scoring models that cannot be explained to a user",
        ],
    ),
    dict(
        key="E7",
        title="Epic: SURFACE: Dashboard, Source & Evidence View, Search",
        labels=["epic", "Dashboard", "Source & Evidence View", "Search & Filters", "must"],
        goal="Give users one clear view of what is new, active, growing or declining, with the evidence behind every figure.",
        scope=[
            "PULSE dashboard surfacing changes and trends",
            "Source & Evidence View linking every figure to its underlying record",
            "Entity list and detail views",
            "Search and filters by company, person, topic, category, geography, source and period (SHOULD)",
        ],
        success=[
            "Every surfaced figure links to its underlying record",
            "The core demonstration does not depend on optional AI features",
        ],
        out_of_scope=[],
    ),
    dict(
        key="E8",
        title="Epic: Alerts & Watchlists",
        labels=["epic", "Alerts & Watchlists", "should"],
        goal="Let users follow selected companies, people or topics and be told when something they care about changes.",
        scope=[
            "Watchlists per user",
            "Alert rules on defined changes or score thresholds",
            "In-app notifications, with email as an option",
        ],
        success=[
            "A user can follow an entity and see an alert after a sync that changes it",
        ],
        out_of_scope=[],
    ),
    dict(
        key="E9",
        title="Epic: Security, Users & Administration",
        labels=["epic", "Admin & Configuration", "security", "should"],
        goal="Protect the data PULSE holds and let administrators configure it.",
        scope=[
            "Authentication and roles (SHOULD, once the demo needs more than one user)",
            "Management of sources, categories, thresholds and sync frequency (COULD, beyond what the demo requires)",
            "Audit trail of administrative actions",
            "Privacy controls for personal data (retention, access)",
        ],
        success=[
            "Only authorized users can access data and configuration, and the wiki documents how",
        ],
        out_of_scope=[],
    ),
    dict(
        key="E10",
        title="Epic: Reports & PULSE API",
        labels=["epic", "Reports", "PULSE API", "could"],
        goal="Share PULSE insights outside the app through reports and an API.",
        scope=[
            "Weekly, monthly or custom summaries of activity and important changes",
            "Read-only API exposing normalized data, scores and trends",
            "API documentation (for example OpenAPI)",
        ],
        success=[
            "A third-party client can fetch entity data and scores through a documented API",
        ],
        out_of_scope=[
            "Any work here before the core Collect to Surface workflow is stable",
        ],
    ),
    dict(
        key="E11",
        title="Epic: Classification, Relationships & Optional AI",
        labels=["epic", "Topic Classification", "Relationship Mapping", "AI Summaries", "could"],
        goal="Enrich the ecosystem with tags, relationships and optional AI-assisted interpretation.",
        scope=[
            "Tags and categories, with optional AI-assisted classification",
            "Relationship mapping between companies, people, content, topics and events, using explicit relationships from the sources",
            "Optional AI summaries of selected changes, organizations or topics",
            "Ask PULSE: natural-language questions grounded in the connected data (stretch)",
        ],
        success=[
            "Any AI feature is grounded in PULSE data and can be switched off without breaking the core demo",
        ],
        out_of_scope=[
            "Making the core demonstration depend on AI",
        ],
    ),
    dict(
        key="E12",
        title="Epic: Project Management, Documentation & Professional Practice",
        labels=["epic", "documentation", "project-mgmt"],
        goal="Deliver the non-code work graded at every release: design documents, planning, legal, ethics, economics and learning.",
        scope=[
            "Wiki, architecture and domain diagrams, UI mockups",
            "Problem statement and risk register",
            "Legal, licensing and privacy review",
            "Societal impact, ethics and diversity statements",
            "Business model and cost estimate",
            "Iteration planning, story points and velocity",
            "Team charter and stakeholder meeting log",
            "Learning log",
            "Updated competitive comparison and research source log (proposal outputs)",
            "Refreshed for each release: Release 1 (Nov 17, 2026), Release 2 (Feb 5, 2027), Final Release (Apr 13, 2027)",
        ],
        success=[
            "Every graded item in the release rubric has an up-to-date wiki page or artifact at each release",
        ],
        out_of_scope=[],
    ),
    dict(
        key="E13",
        title="Epic: Validation, Rollout & User Feedback",
        labels=["epic", "project-mgmt"],
        goal="Put PULSE in front of the sponsor and users, learn from it, and feed what we learn back into the plan.",
        scope=[
            "Rollout strategy and user study plan",
            "Tagged releases with release notes: Release 1, Release 2, Final Release",
            "Sponsor demos and user studies",
            "Usage logging to support studies",
            "Turning feedback into backlog changes",
            "Release presentations, final group presentation, peer evaluations and stakeholder feedback (by Apr 13, 2027)",
        ],
        success=[
            "Each release is delivered to a real audience, and their feedback visibly changes the plan",
        ],
        out_of_scope=[],
    ),
]

# ------------------------------------------------------------ RELEASE 1 ISSUES
# kind: "code" | "docs" | "spike"  (selects the definition of done)
# points: story points on the Fibonacci scale (1, 2, 3, 5, 8, 13)
ISSUES = [
    # ---------------------------------------------------------- Foundation
    dict(
        key="S1-01", epic="E1", iteration=1, kind="spike", points=3,
        title="Select tech stack and justify frameworks and libraries",
        labels=["spike", "DevOps & CI", "infra", "must"],
        goal="Choose the backend, frontend, database and key libraries, and record why, so the whole team builds on one agreed stack.",
        context="The rubric asks for a justification of frameworks and libraries (UET-2) and looks at how the design evolved (DE-2). The proposal suggests rapidfuzz for fuzzy matching and a store holding entities, source records and historical states; the team may choose otherwise as long as the reasons are recorded.",
        ac=[
            "At least two options compared for each of: backend framework, frontend framework, database, test framework",
            "Comparison criteria include team familiarity, support for data processing and fuzzy matching, testing and mocking support, Docker support and licence",
            "Each major choice recorded as an Architecture Decision Record (ADR) in the wiki",
            "Libraries chosen for fuzzy matching, phone number normalization, logging and CSV/JSON parsing",
            "Decision confirmed by the team in a meeting and recorded in the meeting log",
        ],
        tasks=[
            "List candidate options per category",
            "Build a short comparison table per category",
            "Build a small hello-world with the top backend option if the team is split",
            "Write the ADRs",
            "Present to the team and confirm",
        ],
        blocked_by=[],
        blocks=["S1-02", "S1-03", "S1-05", "S1-07", "S1-11", "S1-14"],
        out_of_scope=[],
        rubric=["UET-2 Select appropriate tools", "DE-2 Idea generation and selection", "Code: Using best practices for framework"],
    ),
    dict(
        key="S1-02", epic="E1", iteration=1, kind="code", points=2,
        title="Set up repository structure and contribution conventions",
        labels=["task", "DevOps & CI", "infra", "must"],
        goal="Give the repo a clean, logical layout and shared conventions, so every commit, branch and PR is consistent and traceable to an issue.",
        context="The rubric grades directory structure and commit messages, and expects commits to reference issue numbers. It also asks for README files explaining any directory whose purpose is not obvious.",
        ac=[
            "Top-level layout separates source, tests, configuration and docs, and groups code by layer (for example api, domain/services, connectors, frontend)",
            "A README in every directory whose purpose is not obvious",
            "Branch strategy documented: protected `main`, feature branches named `feature/<issue>-short-name`",
            "Commit convention documented: imperative mood and an issue reference, for example `Add CSV schema validation (#12)`",
            "[x] Issue templates (user story, task, bug) and a PR template with a `Closes #` line and a checklist (done in #1)",
            "`CONTRIBUTING.md` summarizing the conventions",
            "Wiki page \"Architecture & Directory Structure\" explains how folders map to layers (finalized with {S1-14})",
        ],
        tasks=[
            "Create the folder skeleton",
            "Write the directory READMEs",
            "[x] Add issue and PR templates under `.github/` (done in #1)",
            "Write `CONTRIBUTING.md`",
            "Start the wiki page",
        ],
        blocked_by=["S1-01"],
        blocks=["S1-03"],
        out_of_scope=[],
        rubric=["Code: Commit change description", "Code: Directory/package structure", "PA-3 Problem solving (linking work to stories)"],
    ),
    dict(
        key="S1-03", epic="E1", iteration=2, kind="code", points=2,
        title="Configure linters, formatters and pre-commit hooks",
        labels=["task", "DevOps & CI", "must"],
        goal="Enforce one code style automatically so reviews focus on logic, not formatting.",
        context="The rubric expects a defined style guide, linter and formatter configuration in the repo, and a wiki page naming them.",
        ac=[
            "Linter and formatter configured for backend and frontend, following the language's standard style guide, with config files committed",
            "`.editorconfig` for indentation, line endings and line length",
            "Pre-commit hooks run the formatter and linter on staged files",
            "Recommended IDE settings and extensions committed (for example `.vscode/extensions.json`)",
            "All existing code passes with zero lint errors",
            "Wiki page \"Code Style\" names the linter, formatter and style guide, and explains how to run them",
        ],
        tasks=[
            "Add linter and formatter config for the backend",
            "Add linter and formatter config for the frontend",
            "Set up pre-commit hooks",
            "Add IDE recommendations",
            "Write the wiki page",
        ],
        blocked_by=["S1-01", "S1-02"],
        blocks=["S1-04"],
        out_of_scope=[],
        rubric=["Code: Code style and readability", "UET-1 Use appropriate engineering tools"],
    ),
    dict(
        key="S1-04", epic="E1", iteration=2, kind="code", points=5,
        title="Set up CI pipeline on every push and pull request",
        labels=["task", "DevOps & CI", "must"],
        goal="Run lint, tests and builds automatically so broken code never reaches `main`.",
        context="The rubric expects CI to run tests and linters on every push or PR, fail the build on errors, and be described in the wiki. A multi-stage pipeline with extra checks scores highest.",
        ac=[
            "GitHub Actions workflow runs on push to any branch and on PRs to `main`",
            "Stages: install, lint, unit tests, integration tests, coverage report, Docker image build",
            "The build fails on lint errors, test failures, or coverage below the agreed threshold",
            "Branch protection on `main` requires passing CI and one approving review",
            "Coverage summary visible on every PR",
            "CI status badge in the README",
            "Wiki page \"CI/CD Pipeline\" lists every stage and what it checks",
        ],
        tasks=[
            "Write the workflow file",
            "Cache dependencies to keep runs fast",
            "Publish the coverage report",
            "Configure branch protection",
            "Write the wiki page",
        ],
        blocked_by=["S1-03", "S1-05", "S1-07"],
        blocks=[],
        out_of_scope=["Automatic deployment (revisit when a hosted demo is needed for rollout)"],
        rubric=["Code: Continuous integration", "UET-1 Use appropriate engineering tools"],
    ),
    dict(
        key="S1-05", epic="E1", iteration=2, kind="code", points=5,
        title="Containerize the application with Docker Compose",
        labels=["task", "DevOps & CI", "must"],
        goal="Start the whole stack with one command on any machine.",
        context="The rubric expects working Dockerfiles, a docker-compose file for services such as the database, a `.dockerignore`, and README instructions.",
        ac=[
            "Dockerfile for the backend and the frontend (multi-stage where it reduces image size)",
            "`docker-compose.yml` starts backend, frontend and database with one command",
            "`.dockerignore` keeps images clean (no dependency folders, `.env`, `notes/`)",
            "All configuration through environment variables, each documented in `.env.example`",
            "Database data persisted in a named volume; migrations run on startup or through a documented command",
            "README section \"Run with Docker\" with build and run steps, tested by a teammate on a clean machine",
        ],
        tasks=[
            "Write the backend Dockerfile",
            "Write the frontend Dockerfile",
            "Write `docker-compose.yml` with the database service",
            "Add `.dockerignore` and `.env.example`",
            "Update the README and have a teammate test it",
        ],
        blocked_by=["S1-01"],
        blocks=["S1-04"],
        out_of_scope=[],
        rubric=["Code: Containerization", "CO-3 Documentation"],
    ),
    dict(
        key="S1-06", epic="E1", iteration=2, kind="code", points=5,
        title="Add central logging and error handling foundation",
        labels=["task", "infra", "must"],
        goal="Make every part of PULSE log and fail the same way, so problems are easy to debug and users never see raw errors.",
        context="The rubric grades logging (levels, central utility, no sensitive data) and error handling (meaningful messages, no crashes, custom exceptions). Logging also supports the user studies graded under INV-3.",
        ac=[
            "One central logger utility used by every backend module; no raw print or console output",
            "Levels DEBUG, INFO, WARN and ERROR used consistently; level configurable through an environment variable",
            "Key events logged: startup, shutdown, every import or sync run with record counts, and errors with stack traces",
            "Structured (JSON) log format with timestamp, level, module and request or run id",
            "Personal data (emails, phone numbers) and secrets are never logged, or are masked",
            "Global error handler returns a standard error response (code, message, details) and never exposes stack traces to clients",
            "Custom exception types for validation errors, not-found errors and connector failures",
            "Frontend: central logger wrapper and user-friendly error display",
            "Wiki page \"Logging & Error Handling\" names the logging libraries for frontend and backend and links to their config files",
        ],
        tasks=[
            "Configure the backend logger",
            "Add request and run id middleware",
            "Implement the global error handler and custom exceptions",
            "Add the frontend logger and error display",
            "Write the wiki page",
        ],
        blocked_by=["S1-01"],
        blocks=["S1-10"],
        out_of_scope=[],
        rubric=["Code: Logging statements", "Code: Error handling", "INV-3 Logging infrastructure"],
    ),
    dict(
        key="S1-07", epic="E1", iteration=2, kind="code", points=3,
        title="Set up test framework, mocking and coverage tooling",
        labels=["task", "DevOps & CI", "must"],
        goal="Make it easy to write tests that break when core logic breaks, and measure how much is covered.",
        context="The rubric expects unit and integration tests for the main use cases, substantive use of mocks, a coverage tool, and a wiki page describing what is tested. At least 50 percent coverage is \"expected\"; 80 percent with edge cases is \"exceptional\".",
        ac=[
            "Unit and integration test frameworks set up for backend and frontend",
            "Mocking library chosen and shown in an example test (for example a mocked source connector)",
            "Integration tests run against a real test database in Docker",
            "Coverage tool reports line and branch coverage; 50 percent minimum enforced in CI, with 80 percent as the target for core logic modules",
            "Test folder layout mirrors the source layout",
            "Wiki page \"Testing Strategy\": what is covered, which mocking frameworks are used, how to run tests, which coverage tool is used",
        ],
        tasks=[
            "Set up backend unit and integration testing",
            "Set up frontend component testing",
            "Configure coverage reporting and threshold",
            "Write the example mocked test",
            "Write the wiki page",
        ],
        blocked_by=["S1-01"],
        blocks=["S1-04"],
        out_of_scope=[],
        rubric=["Code: Tests"],
    ),
    dict(
        key="S1-08", epic="E1", iteration=3, kind="code", points=5,
        title="Establish security baseline",
        labels=["task", "security", "must"],
        goal="Apply standard security practices from the start and document the threats PULSE faces.",
        context="The rubric expects `.env` usage, input validation, protection against injection, and a wiki page on security considerations with links to code. PULSE accepts file uploads and stores personal data about people, so both need specific attention. Authentication is planned under {E9}.",
        ac=[
            "No secrets in the repo: `.env` git-ignored, `.env.example` committed, GitHub secret scanning enabled",
            "All API inputs validated with schemas (types, lengths, formats); uploaded files limited by size and type",
            "Database access only through the ORM or parameterized queries; no SQL built from strings",
            "CORS restricted to the frontend origin",
            "Dependabot (or equivalent) enabled for dependency updates and vulnerability alerts",
            "Security headers set on API responses",
            "Wiki page \"Security\" lists the threats considered (file upload abuse, injection, personal data exposure), how each is handled with links to code, and why authentication is scheduled for a later release",
        ],
        tasks=[
            "Add request schema validation",
            "Add upload limits",
            "Configure CORS and security headers",
            "Enable Dependabot and secret scanning",
            "Write the wiki page",
        ],
        blocked_by=["S1-01"],
        blocks=[],
        out_of_scope=["Authentication and roles (see {E9})"],
        rubric=["Code: Security strategy and implementation of practices"],
    ),
    # ------------------------------------------------------ Thin working slice
    dict(
        key="S1-09", epic="E2", iteration=1, kind="spike", points=5,
        title="Identify and validate 2 to 3 real data sources with the sponsor",
        labels=["spike", "Data Connectors", "must"],
        goal="Agree with deRabane which real sources PULSE will connect to, and confirm we can use them technically and legally.",
        context="The proposal targets about 2 to 3 representative sources plus CSV/JSON import. Synthetic data may be used for connector testing but not for the Entity Resolution evaluation, so we need real sources whose records genuinely overlap.",
        ac=[
            "Shortlist of candidate sources (APIs, directories, event platforms, CRM exports) with the entities each one exposes",
            "For each source: access method, authentication, rate limits, pagination, data format, terms of service, and what personal data it contains",
            "At least two chosen sources confirmed to contain overlapping companies or people (needed for the Entity Resolution evaluation)",
            "Sample export of each chosen source stored in a shared, access-controlled location, not committed to the repo if it contains personal data",
            "Choice confirmed by the sponsor and recorded in the meeting log",
            "Fallback documented: sponsor-approved exports if an API becomes unavailable",
        ],
        tasks=[
            "Ask the sponsor for candidate sources and existing exports",
            "Investigate each candidate's API and terms",
            "Check overlap between samples",
            "Present the findings to the sponsor",
            "Write the wiki page \"Data Sources\"",
        ],
        blocked_by=[],
        blocks=["S1-10", "S1-12", "S1-20"],
        out_of_scope=["Building the source adapters (later iterations under {E2})"],
        rubric=["PA-1 Problem identification (mitigating major risks)", "PR-1 Legal aspects", "PR-2 Stakeholder interaction"],
    ),
    dict(
        key="S1-10", epic="E2", iteration=3, kind="code", points=8,
        title="Import companies and people from CSV and JSON files",
        labels=["user-story", "Data Connectors", "must"],
        story=("PULSE analyst", "to upload a CSV or JSON file of companies and people", "information from any system can enter PULSE even without a dedicated connector"),
        context="CSV and JSON import is the universal starting point in the proposal. Raw payloads are kept as an archive for reprocessing and debugging (proposal risk: Data Integration).",
        ac=[
            "Upload endpoint and UI accept CSV and JSON files up to a configured size limit",
            "A documented field mapping (with a template file) maps input columns to the data model",
            "Every row validated for required fields, types and formats; invalid rows reported with row number and reason while valid rows are still imported",
            "The raw file and every raw record stored unchanged and linked to their import run",
            "Every import recorded as a sync run with source, timestamp and counts of imported and rejected rows",
            "Imported records pass through the normalization module ({S1-12}), storing normalized fields next to raw values",
            "A 5,000-row file imports without timing out (batch inserts)",
            "Unit tests for parsing and validation using mocks; one integration test importing a sample file end to end",
        ],
        tasks=[
            "Define the field mapping and template files",
            "Implement parsing and row validation",
            "Store raw payloads and sync runs",
            "Call the normalization module",
            "Build the upload UI with the error report",
            "Write the tests",
        ],
        blocked_by=["S1-06", "S1-09", "S1-11", "S1-12"],
        blocks=["S1-13"],
        out_of_scope=["Connectors that call external APIs (later iterations under {E2})", "Matching and merging duplicates ({E3})"],
        rubric=["Code: Substantial implementation beyond CRUD", "Code: Error handling", "Code: Performance considerations", "DE-4 Validation and implementation"],
    ),
    dict(
        key="S1-11", epic="E4", iteration=3, kind="code", points=8,
        title="Design and implement the Unified Data Model v0",
        labels=["user-story", "Unified Data Model", "must"],
        story=("PULSE developer", "one agreed schema for companies, people, sources and source records", "data from every connector lands in the same structure with its provenance preserved"),
        context="The Unified Data Model is the core of ORGANIZE. Its usefulness depends on Entity Resolution, so every entity must keep links to the source records that support it. This first version covers what Release 1 needs and leaves room for topics, events, activity and historical states.",
        ac=[
            "Entities: Company, Person, Source, SyncRun and SourceRecord (raw payload plus normalized fields), with a provenance link from each entity to its supporting source records",
            "Schema can grow to Topic, Event, Activity and historical states without breaking changes, as shown in the domain model ({S1-15})",
            "Versioned migrations that run from an empty database",
            "Indexes on normalized name, domain and email, and on source and sync run foreign keys, with the reason for each index documented",
            "A data access (repository) layer, so business logic never talks to the database directly",
            "Seed script that loads a small sample dataset for local development",
            "Integration tests for the data access layer",
        ],
        tasks=[
            "Translate the domain model into the schema",
            "Write the migrations",
            "Add the indexes and document why",
            "Implement the data access layer",
            "Write the seed script",
            "Write the tests",
        ],
        blocked_by=["S1-01", "S1-15"],
        blocks=["S1-10", "S1-12", "S1-13"],
        out_of_scope=["Historical snapshots and change tracking ({E5})"],
        rubric=["PA-2 Modelling", "Code: Performance considerations", "Code: Using best practices for framework"],
    ),
    dict(
        key="S1-12", epic="E3", iteration=3, kind="code", points=8,
        title="Identifier normalization module",
        labels=["user-story", "Entity Resolution", "must"],
        story=("PULSE analyst", "names, domains, emails and phone numbers from every source cleaned into one standard format", "records describing the same company or person can be matched reliably later"),
        context="Normalization is the first step of Entity Resolution (proposal section Entity Resolution, Possible approach). A company can show up as `Acme Technologies Inc.` in one source, `ACME Tech` in another and `acme.io` in a third. Tier 1 and Tier 2 matching (Release 2) depend on this module producing consistent keys.\n\nThis module is pure business logic with no I/O, which also makes it our main \"beyond CRUD\" evidence for the Release 1 code rubric.",
        ac=[
            "**Company names:** lowercased, punctuation stripped, whitespace collapsed, legal suffixes removed (`inc`, `ltd`, `llc`, `corp`, `ltée`, `s.a.`, `gmbh`, ...), with the suffix list kept in one config file",
            "**Person names:** lowercased, accents folded (`Émilie` becomes `emilie`), whitespace collapsed, split into first and last name where possible",
            "**Domains:** scheme, `www.`, path, query and trailing slash stripped, then lowercased (`https://www.Acme.io/about` becomes `acme.io`)",
            "**Emails:** lowercased and trimmed; domain extracted as a secondary matching signal",
            "**Phones:** converted to E.164 format; invalid numbers return `null` plus a warning instead of raising an error",
            "Every function is deterministic: the same input always gives the same output",
            "The raw value is never overwritten; the normalized value is stored next to it, keeping provenance",
            "Unit tests cover normal cases, edge cases (empty, unicode, names made only of a suffix such as `Inc.`) and the bad inputs above; module coverage of at least 80 percent",
            "Wiki page \"Beyond-CRUD Flows\" links to this module and explains the rules",
        ],
        tasks=[
            "Define the normalizer interface (one function per identifier type)",
            "Implement company name normalization and the legal suffix config",
            "Implement person name normalization",
            "Implement domain and email normalization",
            "Implement phone normalization with the library chosen in {S1-01}",
            "Write unit tests, including a table of real-world variants from the {S1-09} samples",
            "Expose the module for the CSV/JSON import ({S1-10})",
            "Update the wiki",
        ],
        blocked_by=["S1-01", "S1-09", "S1-11"],
        blocks=["S1-10"],
        extra_blocks="Tier 1 deterministic matching (Release 2, {E3})",
        out_of_scope=["Matching and merging records (Tier 1 and Tier 2, Release 2)", "Fuzzy similarity scoring"],
        rubric=["Code: Substantial implementation beyond CRUD", "Code: Tests", "Code: Error handling", "DE-4 Validation and implementation"],
    ),
    dict(
        key="S1-13", epic="E7", iteration=3, kind="code", points=8,
        title="Browse imported entities with their source provenance",
        labels=["user-story", "Source & Evidence View", "must"],
        story=("PULSE analyst", "to browse imported companies and people and see which source records each one came from", "I can trust and verify what PULSE shows me"),
        context="This is the first SURFACE screen and the first step toward the Source & Evidence View, where every figure links back to its underlying record.",
        ac=[
            "API endpoints list companies and people with server-side pagination (capped page size) and sorting by name",
            "For each entity, the API returns the sources and source records it came from",
            "UI page shows entities in a paginated table with name, type, number of sources and last update",
            "Selecting an entity shows its raw source records and normalized fields side by side",
            "Empty, loading and error states handled with user-friendly messages",
            "Queries use the indexes from {S1-11} and avoid N+1 queries (checked with a query count test or logs)",
            "Component tests for the UI and integration tests for the endpoints",
        ],
        tasks=[
            "Implement the list and detail endpoints with pagination",
            "Build the entity list page",
            "Build the entity detail panel with raw and normalized values",
            "Handle empty, loading and error states",
            "Write the tests",
        ],
        blocked_by=["S1-10", "S1-11", "S1-16"],
        blocks=[],
        out_of_scope=["Search and filters (later under {E7})", "Full entity profile page ({E4})"],
        rubric=["Code: Performance considerations", "Code: Error handling", "Code: Using best practices for framework", "DE-4 Validation and implementation"],
    ),
    # ---------------------------------------------------- Design and modelling
    dict(
        key="S1-14", epic="E12", iteration=2, kind="docs", points=3,
        title="Create the architecture and layer diagram",
        labels=["documentation", "design"],
        goal="Show how PULSE is built, from the six stages down to the components and folders that implement them.",
        context="The rubric grades overall architecture and layers under PA-2, and asks for the wiki to explain how the architecture matches the directory structure. The proposal's illustrative architecture has a connector layer, normalization and Entity Resolution layer, unified data store, analytics layer, application layer and an optional AI layer.",
        ac=[
            "Diagram maps the six stages (Collect, Resolve, Organize, Monitor, Compare, Surface) to layers and components",
            "Deployment view showing the docker-compose containers and how they communicate",
            "Diagram source committed (draw.io, PlantUML or Mermaid) so it can be updated",
            "Wiki page \"Architecture\" embeds the diagram and maps each layer to its folder in the repo",
            "Later changes recorded as ADRs",
        ],
        tasks=[
            "Draft the layer diagram",
            "Draft the deployment view",
            "Review with the team",
            "Publish in the wiki with the folder mapping",
        ],
        blocked_by=["S1-01"],
        blocks=[],
        out_of_scope=[],
        rubric=["PA-2 Modelling (overall architecture and layers)", "Code: Directory/package structure", "CO-4 Oral presentation (use of images)"],
    ),
    dict(
        key="S1-15", epic="E12", iteration=2, kind="docs", points=3,
        title="Create the domain model diagram",
        labels=["documentation", "design", "Unified Data Model"],
        goal="Agree on the entities PULSE manages and how they relate, before the schema is built.",
        context="The rubric grades domain diagrams under PA-2, and the proposal lists documentation of the Unified Data Model as a project output.",
        ac=[
            "Class or ER diagram of all planned entities (Company, Person, Topic, Event, Activity, Source, SyncRun, SourceRecord, match decisions, historical snapshots) with relationships and cardinalities",
            "Shows provenance: how each entity links back to its supporting source records",
            "Shows how match outcomes (Match, Possible Match, No Match with confidence) and historical states are stored",
            "Entities in scope for Release 1 are highlighted",
            "Diagram source committed; wiki page \"Domain Model\" with a glossary of terms",
        ],
        tasks=[
            "Draft the entities and relationships",
            "Review with the team and the sponsor",
            "Publish in the wiki with the glossary",
        ],
        blocked_by=[],
        blocks=["S1-11"],
        out_of_scope=[],
        rubric=["PA-2 Modelling (domain diagrams)"],
    ),
    dict(
        key="S1-16", epic="E12", iteration=2, kind="docs", points=5,
        title="Design UI mockups",
        labels=["documentation", "design", "Dashboard"],
        goal="Agree on what users will see before building the UI.",
        context="The rubric grades mockups under PA-2. Reviewing them with the sponsor also counts as stakeholder feedback.",
        ac=[
            "Mockups for: PULSE dashboard, Source & Evidence View, entity list, entity profile, CSV/JSON import screen, match review queue (low fidelity is fine for later-release screens)",
            "Each mockup names the user story it supports",
            "Made in a shareable tool (for example Figma), with exported images in the wiki",
            "Reviewed with the sponsor; feedback recorded in the meeting log",
        ],
        tasks=[
            "Sketch the Release 1 screens",
            "Sketch the later screens at low fidelity",
            "Review with the sponsor",
            "Publish in the wiki",
        ],
        blocked_by=["S1-17"],
        blocks=["S1-13"],
        out_of_scope=[],
        rubric=["PA-2 Modelling (mockups)", "PR-2 Professional practice (stakeholder feedback)"],
    ),
    dict(
        key="S1-17", epic="E12", iteration=1, kind="docs", points=5,
        title="Write personas and the full user story backlog",
        labels=["documentation", "project-mgmt"],
        goal="Describe who PULSE is for and what they need, as user stories linked to the epics.",
        context="The rubric looks at how communication and artifacts link to stories, as shown by milestones and issues (PA-3).",
        ac=[
            "2 to 3 personas (for example an ecosystem analyst, a program manager at an innovation hub, an administrator), based on sponsor discussion",
            "User stories for every epic in the \"As a / I want / so that\" format, with MoSCoW priority from the proposal",
            "Every story created as an issue, labelled and added as a sub-issue of its parent epic",
            "Release 1 stories have acceptance criteria and story points",
            "Wiki page \"Personas & User Stories\"",
        ],
        tasks=[
            "Draft the personas and validate them with the sponsor",
            "Write stories per epic",
            "Create the issues and link them to epics",
            "Publish in the wiki",
        ],
        blocked_by=[],
        blocks=["S1-16"],
        out_of_scope=[],
        rubric=["PA-1 Problem identification and formulation", "PA-3 Problem solving (linking artifacts to stories)"],
    ),
    # ------------------------------------------- Project management and practice
    dict(
        key="S1-18", epic="E12", iteration=1, kind="docs", points=3,
        title="Write the problem statement and risk register",
        labels=["documentation", "project-mgmt"],
        goal="State clearly what problem PULSE solves, and track the risks that could stop us.",
        context="The rubric grades the description of the problem and whether major risks were mitigated (PA-1). The proposal lists four risks with mitigations and fallbacks, and names a risk register as a project output.",
        ac=[
            "Problem statement: who has the problem, what information is fragmented, why current tools (Quid, AlphaSense, Neo4j, Stardog, Graphwise) do not solve it, and what PULSE will demonstrate",
            "Summary of the MVP boundary (MUST, SHOULD, COULD)",
            "Risk register with, for each risk: description, likelihood, impact, mitigation, fallback, owner and status",
            "Seeded with the proposal's risks (data integration, data quality and Entity Resolution, scope and performance, trust and explainability) plus team risks (schedule, source API availability, personal data)",
            "Reviewed every iteration, with changes recorded",
            "Wiki pages \"Problem Statement\" and \"Risk Register\"",
        ],
        tasks=[
            "Draft the problem statement",
            "Build the risk register",
            "Review both with the team",
            "Publish in the wiki",
        ],
        blocked_by=[],
        blocks=[],
        out_of_scope=[],
        rubric=["PA-1 Problem identification and formulation"],
    ),
    dict(
        key="S1-19", epic="E12", iteration=4, kind="docs", points=5,
        title="Complete the wiki engineering practices pages",
        labels=["documentation"],
        goal="Make sure every wiki page the rubric asks for exists, is accurate and links to the code before Release 1.",
        context="Almost every code criterion in the rubric says \"mention in wiki\". Individual tickets start these pages; this ticket checks them all and fills the gaps.",
        ac=[
            "Wiki home page with navigation to every page below",
            "Architecture & Directory Structure ({S1-02}, {S1-14})",
            "Code Style: linter, formatter and style guide ({S1-03})",
            "Framework Best Practices: at least three practices followed, with links to code",
            "Beyond-CRUD Flows: import pipeline and normalization, with links to code ({S1-10}, {S1-12})",
            "Security ({S1-08})",
            "Performance: at least one bottleneck addressed (indexes, pagination, batch inserts) with evidence such as before and after timings",
            "Logging & Error Handling ({S1-06})",
            "Testing Strategy, including coverage ({S1-07})",
            "CI/CD Pipeline ({S1-04})",
            "Run with Docker ({S1-05})",
            "All links checked; no broken links",
        ],
        tasks=[
            "Audit which pages exist",
            "Write the missing pages",
            "Measure and document the performance evidence",
            "Check every link",
        ],
        blocked_by=["S1-04", "S1-06", "S1-08", "S1-10", "S1-12"],
        blocks=["S1-27"],
        out_of_scope=[],
        rubric=["CO-3 Documentation", "Code: all criteria that require a wiki page"],
    ),
    dict(
        key="S1-20", epic="E12", iteration=3, kind="docs", points=3,
        title="Review legal, licensing and privacy aspects",
        labels=["documentation", "project-mgmt", "security"],
        goal="Make sure PULSE respects licences, source terms, the sponsor's IP and privacy law.",
        context="The rubric grades licence and other legal aspects (PR-1). The proposal leaves IP ownership open for discussion between the students, deRabane and Concordia, and PULSE stores personal information about people.",
        ac=[
            "Repository licence confirmed as compatible with the IP arrangement being discussed with deRabane and Concordia; decision recorded",
            "Inventory of third-party libraries and their licences (generated by a tool where possible)",
            "Terms of service of each chosen data source ({S1-09}) reviewed: storing, reprocessing and displaying the data is allowed",
            "Personal data handling documented: what is stored, why, retention and access, reviewed against Quebec Law 25 and PIPEDA",
            "Confidential sponsor material and sample data kept out of the repo",
            "Wiki page \"Legal & Licensing\"",
        ],
        tasks=[
            "Discuss the licence and IP with the sponsor and the professor",
            "Generate the dependency licence inventory",
            "Review source terms",
            "Write the privacy section",
            "Publish in the wiki",
        ],
        blocked_by=["S1-09"],
        blocks=[],
        out_of_scope=[],
        rubric=["PR-1 Role and responsibilities (licence and legal aspects)", "EE-1 Professional ethics and accountability"],
    ),
    dict(
        key="S1-21", epic="E12", iteration=3, kind="docs", points=3,
        title="Write societal impact, ethics and diversity statements",
        labels=["documentation"],
        goal="Identify how PULSE could harm people or society, how the design reduces that harm, and how the team works ethically and inclusively.",
        context="The rubric grades awareness of societal risks (IES-1), mitigation in the design (IES-2), professional ethics and accountability (EE-1) and a diversity statement (EE-2).",
        ac=[
            "Societal risks identified: profiling of individuals, wrong merges attributing activity to the wrong person or company, stale data shown as current, activity scores biased toward entities with a larger online footprint",
            "A design mitigation for each risk (provenance on every figure, review queue for uncertain matches, transparent scoring, data retention limits)",
            "Sustainability considerations (for example incremental sync instead of full reloads to reduce compute)",
            "Ethics and accountability statement toward the sponsor, users and the people in the data",
            "Team diversity and equity statement",
            "Wiki pages \"Societal Impact\", \"Ethics\" and \"Diversity Statement\"",
        ],
        tasks=[
            "Brainstorm risks as a team",
            "Map each risk to a mitigation",
            "Write the statements",
            "Publish in the wiki",
        ],
        blocked_by=[],
        blocks=[],
        out_of_scope=[],
        rubric=["IES-1 Societal impact", "IES-2 Sustainability in design", "EE-1 Professional ethics", "EE-2 Equity"],
    ),
    dict(
        key="S1-22", epic="E12", iteration=3, kind="docs", points=3,
        title="Define the business model and estimate project cost",
        labels=["documentation", "project-mgmt"],
        goal="Explain how PULSE could make money and what it would cost to build commercially.",
        context="The rubric asks how the project will make money (EPM-2) and how much it would cost if the team were consultants or employees (EPM-3).",
        ac=[
            "Candidate target customers and the value proposition compared with the competitors in the proposal",
            "Pricing model options (for example SaaS tiers by number of sources or seats)",
            "Cost estimate if built by consultants or employees: team size, hours and market rates, plus infrastructure and third-party service costs",
            "All assumptions stated",
            "Wiki page \"Economics\"",
        ],
        tasks=[
            "Research comparable pricing",
            "Draft the business model",
            "Build the cost spreadsheet",
            "Publish in the wiki",
        ],
        blocked_by=[],
        blocks=[],
        out_of_scope=[],
        rubric=["EPM-2 Economics evaluation", "EPM-3 Project planning (project cost)"],
    ),
    dict(
        key="S1-23", epic="E12", iteration=1, kind="docs", points=2,
        title="Plan Iterations 1 to 4 on a GitHub Project board",
        labels=["project-mgmt"],
        goal="Make the plan, the assignments and our velocity visible to the team and the graders.",
        context="The rubric checks that work is assigned to individuals, that there is a plan for at least the current and next iteration (EPM-3), and whether we did enough work at a good velocity (DE-4).",
        ac=[
            "GitHub Project board linked to this repo with Backlog, To Do, In Progress, In Review and Done columns",
            "Every Release 1 issue has an assignee, story points and an iteration milestone",
            "Work balanced across team members",
            "Velocity tracked per iteration (points planned versus completed) and recorded in the wiki",
            "Plan for the current and next iteration kept up to date",
            "Short review and retrospective notes at the end of each iteration",
        ],
        tasks=[
            "Create the Project board",
            "Estimate story points as a team",
            "Assign issues",
            "Set up velocity tracking",
        ],
        blocked_by=[],
        blocks=[],
        out_of_scope=[],
        rubric=["EPM-3 Project planning (assigned to individuals, plan for next iterations)", "DE-4 Validation and implementation (velocity)", "PA-3 Problem solving (milestones and issues)"],
    ),
    dict(
        key="S1-24", epic="E12", iteration=4, kind="docs", points=2,
        title="Keep the team charter and stakeholder meeting log",
        labels=["project-mgmt"],
        goal="Record how the team works and every interaction with the sponsor, professor and each other.",
        context="The rubric grades stakeholder feedback and interactions with the professor and teammates (PR-2), and incorporating feedback into the work plan (INV-4). This log is kept from Iteration 1 and closed at Release 1.",
        ac=[
            "Team charter: roles (for example scrum master, sponsor contact), communication channels, meeting schedule, decision process and conflict resolution",
            "Meeting log in the wiki for every sponsor, professor or TA and team meeting: date, attendees, discussion, decisions and action items linked to issues",
            "Sponsor feedback turned into issues or backlog changes, with links",
            "Kept up to date from Iteration 1 to Release 1",
        ],
        tasks=[
            "Write the team charter in Iteration 1",
            "Create the meeting log template",
            "Log every meeting",
            "Link feedback to issues",
        ],
        blocked_by=[],
        blocks=[],
        out_of_scope=[],
        rubric=["PR-2 Professional practice", "INV-4 Incorporating feedback into the work plan", "ITW-1 to ITW-4 Individual and team work (supports peer evaluation)"],
    ),
    dict(
        key="S1-25", epic="E12", iteration=4, kind="docs", points=2,
        title="Keep a team learning log",
        labels=["documentation"],
        goal="Record what knowledge we were missing and how we acquired it.",
        context="The rubric asks what knowledge the team was missing (LLL-1) and how it was acquired (LLL-2). The log is kept from Iteration 1 and closed at Release 1.",
        ac=[
            "For each member: knowledge gaps identified (for example Entity Resolution techniques, the chosen framework, Docker), how each was filled (courses, documentation, spikes, mentoring) and the result",
            "Links to spikes and ADRs that came out of this learning",
            "Updated every iteration",
            "Wiki page \"Learning Log\"",
        ],
        tasks=[
            "Create the template",
            "Each member adds entries every iteration",
            "Review before Release 1",
        ],
        blocked_by=[],
        blocks=[],
        out_of_scope=[],
        rubric=["LLL-1 Identifying missing knowledge", "LLL-2 Continuous improvement and self-learning"],
    ),
    # ------------------------------------------------- Validation and release
    dict(
        key="S1-26", epic="E13", iteration=3, kind="docs", points=3,
        title="Define the rollout strategy and user study plan",
        labels=["documentation", "project-mgmt"],
        goal="Decide who gets each release, what we want to learn from them and how we will collect it.",
        context="The rubric grades the rollout strategy (INV-1), actual rollouts (INV-2), and logging infrastructure and user studies (INV-3).",
        ac=[
            "Rollout strategy: which audience gets each release (sponsor first, then selected users), what each release demonstrates, and where it runs (local Docker demo or hosted)",
            "Hypotheses to validate per release (for example \"a user can trace any figure to its source in three clicks or fewer\")",
            "User study plan: participants, tasks, metrics and how feedback is recorded",
            "Logging needed for the studies identified and linked to {S1-06}",
            "Wiki page \"Rollout & Validation\"",
        ],
        tasks=[
            "Draft the rollout plan per release",
            "Write the hypotheses",
            "Design the user study",
            "Publish in the wiki",
        ],
        blocked_by=[],
        blocks=["S1-27"],
        out_of_scope=[],
        rubric=["INV-1 Background and hypothesis formulation", "INV-2 Designing experiments", "INV-3 Conducting experiments and collecting data"],
    ),
    dict(
        key="S1-27", epic="E13", iteration=4, kind="code", points=3,
        title="Ship Release 1 (v0.1.0) and collect sponsor feedback",
        labels=["task", "DevOps & CI", "project-mgmt"],
        goal="Deliver Release 1 to the sponsor and turn their feedback into the next plan.",
        context="The rubric asks whether the project has been released and to whom (INV-2), whether feedback made it into the work plan (INV-4), and looks for release notes (CO-3).",
        ac=[
            "`v0.1.0` tagged on `main` and a GitHub Release published",
            "Release notes: features, known limitations, how to run, links to the closed issues",
            "Demo of the implemented slice delivered to deRabane",
            "Feedback recorded in the meeting log and turned into issues for Release 2 planning",
            "Iteration 5 plan updated with the feedback",
        ],
        tasks=[
            "Freeze features and check that CI is green",
            "Write the release notes",
            "Tag and publish the release",
            "Run the sponsor demo",
            "File the feedback as issues",
        ],
        blocked_by=["S1-19", "S1-26"],
        blocks=[],
        out_of_scope=[],
        rubric=["INV-2 Actual rollouts", "INV-4 Incorporating feedback", "CO-3 Documentation (release notes)", "PR-2 Professional practice"],
    ),
    dict(
        key="S1-28", epic="E13", iteration=4, kind="docs", points=5,
        title="Prepare the Release 1 presentation",
        labels=["documentation"],
        goal="Present Release 1 clearly, with visuals and a working demo.",
        context="The rubric grades the oral presentation on being clear and organized and on the use of images (CO-4).",
        ac=[
            "Slides cover the problem, architecture, a demo of the slice, engineering practices and the Release 2 plan",
            "Uses the architecture and domain diagrams ({S1-14}, {S1-15}), mockups and real screenshots",
            "Every member presents a part",
            "At least one full timed rehearsal",
            "Recorded demo ready as a backup for the live demo",
        ],
        tasks=[
            "Outline the talk",
            "Build the slides",
            "Record the backup demo",
            "Rehearse",
        ],
        blocked_by=[],
        blocks=[],
        out_of_scope=[],
        rubric=["CO-4 Oral presentation"],
    ),
]
